// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// digrec_io
// 0x0000 : Control signals
//          bit 0  - ap_start (Read/Write/COH)
//          bit 1  - ap_done (Read/COR)
//          bit 2  - ap_idle (Read)
//          bit 3  - ap_ready (Read)
//          bit 7  - auto_restart (Read/Write)
//          others - reserved
// 0x0004 : Global Interrupt Enable Register
//          bit 0  - Global Interrupt Enable (Read/Write)
//          others - reserved
// 0x0008 : IP Interrupt Enable Register (Read/Write)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x000c : IP Interrupt Status Register (Read/TOW)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x1000 ~
// 0x1fff : Memory 'inputData' (784 * 32b)
//          Word n : bit [31:0] - inputData[n]
// 0x2000 ~
// 0x203f : Memory 'output_r' (10 * 32b)
//          Word n : bit [31:0] - output_r[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDIGITRECOGNIZER_DIGREC_IO_ADDR_AP_CTRL        0x0000
#define XDIGITRECOGNIZER_DIGREC_IO_ADDR_GIE            0x0004
#define XDIGITRECOGNIZER_DIGREC_IO_ADDR_IER            0x0008
#define XDIGITRECOGNIZER_DIGREC_IO_ADDR_ISR            0x000c
#define XDIGITRECOGNIZER_DIGREC_IO_ADDR_INPUTDATA_BASE 0x1000
#define XDIGITRECOGNIZER_DIGREC_IO_ADDR_INPUTDATA_HIGH 0x1fff
#define XDIGITRECOGNIZER_DIGREC_IO_WIDTH_INPUTDATA     32
#define XDIGITRECOGNIZER_DIGREC_IO_DEPTH_INPUTDATA     784
#define XDIGITRECOGNIZER_DIGREC_IO_ADDR_OUTPUT_R_BASE  0x2000
#define XDIGITRECOGNIZER_DIGREC_IO_ADDR_OUTPUT_R_HIGH  0x203f
#define XDIGITRECOGNIZER_DIGREC_IO_WIDTH_OUTPUT_R      32
#define XDIGITRECOGNIZER_DIGREC_IO_DEPTH_OUTPUT_R      10

