// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xneuroninitandcompute3hardcoded.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XNeuroninitandcompute3hardcoded_CfgInitialize(XNeuroninitandcompute3hardcoded *InstancePtr, XNeuroninitandcompute3hardcoded_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Neuron_hard_io_BaseAddress = ConfigPtr->Neuron_hard_io_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XNeuroninitandcompute3hardcoded_Start(XNeuroninitandcompute3hardcoded *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_AP_CTRL) & 0x80;
    XNeuroninitandcompute3hardcoded_WriteReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_AP_CTRL, Data | 0x01);
}

u32 XNeuroninitandcompute3hardcoded_IsDone(XNeuroninitandcompute3hardcoded *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XNeuroninitandcompute3hardcoded_IsIdle(XNeuroninitandcompute3hardcoded *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XNeuroninitandcompute3hardcoded_IsReady(XNeuroninitandcompute3hardcoded *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XNeuroninitandcompute3hardcoded_EnableAutoRestart(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuroninitandcompute3hardcoded_WriteReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_AP_CTRL, 0x80);
}

void XNeuroninitandcompute3hardcoded_DisableAutoRestart(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuroninitandcompute3hardcoded_WriteReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_AP_CTRL, 0);
}

u64 XNeuroninitandcompute3hardcoded_Get_output_V(XNeuroninitandcompute3hardcoded *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_OUTPUT_V_DATA);
    Data += (u64)XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_OUTPUT_V_DATA + 4) << 32;
    return Data;
}

u32 XNeuroninitandcompute3hardcoded_Get_output_V_vld(XNeuroninitandcompute3hardcoded *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_OUTPUT_V_CTRL);
    return Data & 0x1;
}

u32 XNeuroninitandcompute3hardcoded_Get_inputData_V_BaseAddress(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Neuron_hard_io_BaseAddress + XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE);
}

u32 XNeuroninitandcompute3hardcoded_Get_inputData_V_HighAddress(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Neuron_hard_io_BaseAddress + XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_HIGH);
}

u32 XNeuroninitandcompute3hardcoded_Get_inputData_V_TotalBytes(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_HIGH - XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE + 1);
}

u32 XNeuroninitandcompute3hardcoded_Get_inputData_V_BitWidth(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_WIDTH_INPUTDATA_V;
}

u32 XNeuroninitandcompute3hardcoded_Get_inputData_V_Depth(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_DEPTH_INPUTDATA_V;
}

u32 XNeuroninitandcompute3hardcoded_Write_inputData_V_Words(XNeuroninitandcompute3hardcoded *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_HIGH - XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Neuron_hard_io_BaseAddress + XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XNeuroninitandcompute3hardcoded_Read_inputData_V_Words(XNeuroninitandcompute3hardcoded *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_HIGH - XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Neuron_hard_io_BaseAddress + XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XNeuroninitandcompute3hardcoded_Write_inputData_V_Bytes(XNeuroninitandcompute3hardcoded *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_HIGH - XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Neuron_hard_io_BaseAddress + XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XNeuroninitandcompute3hardcoded_Read_inputData_V_Bytes(XNeuroninitandcompute3hardcoded *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_HIGH - XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Neuron_hard_io_BaseAddress + XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_INPUTDATA_V_BASE + offset + i);
    }
    return length;
}

void XNeuroninitandcompute3hardcoded_InterruptGlobalEnable(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuroninitandcompute3hardcoded_WriteReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_GIE, 1);
}

void XNeuroninitandcompute3hardcoded_InterruptGlobalDisable(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuroninitandcompute3hardcoded_WriteReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_GIE, 0);
}

void XNeuroninitandcompute3hardcoded_InterruptEnable(XNeuroninitandcompute3hardcoded *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_IER);
    XNeuroninitandcompute3hardcoded_WriteReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_IER, Register | Mask);
}

void XNeuroninitandcompute3hardcoded_InterruptDisable(XNeuroninitandcompute3hardcoded *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_IER);
    XNeuroninitandcompute3hardcoded_WriteReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_IER, Register & (~Mask));
}

void XNeuroninitandcompute3hardcoded_InterruptClear(XNeuroninitandcompute3hardcoded *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuroninitandcompute3hardcoded_WriteReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_ISR, Mask);
}

u32 XNeuroninitandcompute3hardcoded_InterruptGetEnabled(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_IER);
}

u32 XNeuroninitandcompute3hardcoded_InterruptGetStatus(XNeuroninitandcompute3hardcoded *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNeuroninitandcompute3hardcoded_ReadReg(InstancePtr->Neuron_hard_io_BaseAddress, XNEURONINITANDCOMPUTE3HARDCODED_NEURON_HARD_IO_ADDR_ISR);
}

