// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_ho_loop_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_ho_loop_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_ho_loop_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_state1 = "1";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_state2 = "10";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_state3 = "100";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_pp0_stage1 = "10000";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_pp0_stage2 = "100000";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_pp0_stage3 = "1000000";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_pp0_stage4 = "10000000";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_pp0_stage5 = "100000000";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_pp0_stage6 = "1000000000";
const sc_lv<11> Loop_ho_loop_proc::ap_ST_fsm_state17 = "10000000000";
const sc_lv<32> Loop_ho_loop_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Loop_ho_loop_proc::ap_const_boolean_1 = true;
const sc_lv<32> Loop_ho_loop_proc::ap_const_lv32_1 = "1";
const sc_lv<1> Loop_ho_loop_proc::ap_const_lv1_0 = "0";
const sc_lv<32> Loop_ho_loop_proc::ap_const_lv32_2 = "10";
const sc_lv<32> Loop_ho_loop_proc::ap_const_lv32_3 = "11";
const bool Loop_ho_loop_proc::ap_const_boolean_0 = false;
const sc_lv<32> Loop_ho_loop_proc::ap_const_lv32_4 = "100";
const sc_lv<32> Loop_ho_loop_proc::ap_const_lv32_8 = "1000";
const sc_lv<1> Loop_ho_loop_proc::ap_const_lv1_1 = "1";
const sc_lv<32> Loop_ho_loop_proc::ap_const_lv32_9 = "1001";
const sc_lv<32> Loop_ho_loop_proc::ap_const_lv32_A = "1010";
const sc_lv<4> Loop_ho_loop_proc::ap_const_lv4_0 = "0000";
const sc_lv<6> Loop_ho_loop_proc::ap_const_lv6_1 = "1";
const sc_lv<32> Loop_ho_loop_proc::ap_const_lv32_5 = "101";
const sc_lv<4> Loop_ho_loop_proc::ap_const_lv4_A = "1010";
const sc_lv<4> Loop_ho_loop_proc::ap_const_lv4_1 = "1";
const sc_lv<5> Loop_ho_loop_proc::ap_const_lv5_0 = "00000";
const sc_lv<6> Loop_ho_loop_proc::ap_const_lv6_21 = "100001";
const sc_lv<6> Loop_ho_loop_proc::ap_const_lv6_3F = "111111";

Loop_ho_loop_proc::Loop_ho_loop_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    hiddenToOutputWeight_U = new Loop_ho_loop_procfYi("hiddenToOutputWeight_U");
    hiddenToOutputWeight_U->clk(ap_clk);
    hiddenToOutputWeight_U->reset(ap_rst);
    hiddenToOutputWeight_U->address0(hiddenToOutputWeight_address0);
    hiddenToOutputWeight_U->ce0(hiddenToOutputWeight_ce0);
    hiddenToOutputWeight_U->q0(hiddenToOutputWeight_q0);
    digitRecognizer_fcud_x_U6 = new digitRecognizer_fcud<1,7,32,32,32>("digitRecognizer_fcud_x_U6");
    digitRecognizer_fcud_x_U6->clk(ap_clk);
    digitRecognizer_fcud_x_U6->reset(ap_rst);
    digitRecognizer_fcud_x_U6->din0(sum1_reg_121);
    digitRecognizer_fcud_x_U6->din1(tmp_8_reg_278);
    digitRecognizer_fcud_x_U6->ce(ap_var_for_const0);
    digitRecognizer_fcud_x_U6->dout(grp_fu_132_p2);
    digitRecognizer_fdEe_x_U7 = new digitRecognizer_fdEe<1,4,32,32,32>("digitRecognizer_fdEe_x_U7");
    digitRecognizer_fdEe_x_U7->clk(ap_clk);
    digitRecognizer_fdEe_x_U7->reset(ap_rst);
    digitRecognizer_fdEe_x_U7->din0(hiddenToOutputWeight_2_reg_268);
    digitRecognizer_fdEe_x_U7->din1(hiddenOut_load_reg_273);
    digitRecognizer_fdEe_x_U7->ce(ap_var_for_const0);
    digitRecognizer_fdEe_x_U7->dout(grp_fu_137_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage1_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage1_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage2_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage2_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage3_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage4_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage5_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage5_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage6_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage6_flag00011011);

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage6_iter0);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state12_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state13_pp0_stage2_iter1);

    SC_METHOD(thread_ap_block_state14_pp0_stage3_iter1);

    SC_METHOD(thread_ap_block_state15_pp0_stage4_iter1);

    SC_METHOD(thread_ap_block_state16_pp0_stage5_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state7_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state8_pp0_stage4_iter0);

    SC_METHOD(thread_ap_block_state9_pp0_stage5_iter0);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( exitcond_fu_184_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_141_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_141_p2 );

    SC_METHOD(thread_exitcond1_fu_141_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( o_1_reg_98 );

    SC_METHOD(thread_exitcond_fu_184_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( i_1_phi_fu_114_p4 );

    SC_METHOD(thread_hiddenOut_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( tmp_4_cast_fu_210_p1 );

    SC_METHOD(thread_hiddenOut_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_hiddenToOutputWeight_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( tmp_9_cast_fu_175_p1 );
    sensitive << ( tmp_10_cast_fu_199_p1 );

    SC_METHOD(thread_hiddenToOutputWeight_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_i_1_phi_fu_114_p4);
    sensitive << ( i_1_reg_110 );
    sensitive << ( exitcond_reg_249 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_reg_263 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_i_fu_215_p2);
    sensitive << ( i_1_phi_fu_114_p4 );

    SC_METHOD(thread_o_fu_147_p2);
    sensitive << ( o_1_reg_98 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( tmp_1_reg_239 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( sum1_reg_121 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_p_shl_cast_fu_165_p1);
    sensitive << ( tmp_fu_157_p3 );

    SC_METHOD(thread_tmp_10_cast_fu_199_p1);
    sensitive << ( tmp_s_fu_194_p2 );

    SC_METHOD(thread_tmp_1_cast_fu_153_p1);
    sensitive << ( o_1_reg_98 );

    SC_METHOD(thread_tmp_1_fu_180_p1);
    sensitive << ( o_1_reg_98 );

    SC_METHOD(thread_tmp_4_cast_fu_210_p1);
    sensitive << ( tmp_4_fu_204_p2 );

    SC_METHOD(thread_tmp_4_fu_204_p2);
    sensitive << ( i_1_phi_fu_114_p4 );

    SC_METHOD(thread_tmp_9_cast_fu_175_p1);
    sensitive << ( tmp_9_fu_169_p2 );

    SC_METHOD(thread_tmp_9_fu_169_p2);
    sensitive << ( tmp_1_cast_fu_153_p1 );
    sensitive << ( p_shl_cast_fu_165_p1 );

    SC_METHOD(thread_tmp_cast_fu_190_p1);
    sensitive << ( i_1_phi_fu_114_p4 );

    SC_METHOD(thread_tmp_fu_157_p3);
    sensitive << ( o_1_reg_98 );

    SC_METHOD(thread_tmp_s_fu_194_p2);
    sensitive << ( tmp_9_reg_229 );
    sensitive << ( tmp_cast_fu_190_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_141_p2 );
    sensitive << ( exitcond_fu_184_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage5 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00011011 );
    sensitive << ( ap_block_pp0_stage6_flag00011011 );
    sensitive << ( ap_block_pp0_stage5_flag00011011 );
    sensitive << ( ap_block_pp0_stage1_flag00011011 );
    sensitive << ( ap_block_pp0_stage2_flag00011011 );
    sensitive << ( ap_block_pp0_stage3_flag00011011 );
    sensitive << ( ap_block_pp0_stage4_flag00011011 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_ho_loop_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, hiddenOut_address0, "(port)hiddenOut_address0");
    sc_trace(mVcdFile, hiddenOut_ce0, "(port)hiddenOut_ce0");
    sc_trace(mVcdFile, hiddenOut_q0, "(port)hiddenOut_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, hiddenToOutputWeight_address0, "hiddenToOutputWeight_address0");
    sc_trace(mVcdFile, hiddenToOutputWeight_ce0, "hiddenToOutputWeight_ce0");
    sc_trace(mVcdFile, hiddenToOutputWeight_q0, "hiddenToOutputWeight_q0");
    sc_trace(mVcdFile, i_1_reg_110, "i_1_reg_110");
    sc_trace(mVcdFile, sum1_reg_121, "sum1_reg_121");
    sc_trace(mVcdFile, o_fu_147_p2, "o_fu_147_p2");
    sc_trace(mVcdFile, o_reg_224, "o_reg_224");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_9_fu_169_p2, "tmp_9_fu_169_p2");
    sc_trace(mVcdFile, tmp_9_reg_229, "tmp_9_reg_229");
    sc_trace(mVcdFile, exitcond1_fu_141_p2, "exitcond1_fu_141_p2");
    sc_trace(mVcdFile, tmp_1_fu_180_p1, "tmp_1_fu_180_p1");
    sc_trace(mVcdFile, tmp_1_reg_239, "tmp_1_reg_239");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond_fu_184_p2, "exitcond_fu_184_p2");
    sc_trace(mVcdFile, exitcond_reg_249, "exitcond_reg_249");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter1, "ap_block_state11_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011001, "ap_block_pp0_stage0_flag00011001");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_exitcond_reg_249, "ap_reg_pp0_iter1_exitcond_reg_249");
    sc_trace(mVcdFile, i_fu_215_p2, "i_fu_215_p2");
    sc_trace(mVcdFile, i_reg_263, "i_reg_263");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, hiddenToOutputWeight_2_reg_268, "hiddenToOutputWeight_2_reg_268");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter0, "ap_block_state5_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage1_iter1, "ap_block_state12_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_flag00011001, "ap_block_pp0_stage1_flag00011001");
    sc_trace(mVcdFile, hiddenOut_load_reg_273, "hiddenOut_load_reg_273");
    sc_trace(mVcdFile, grp_fu_137_p2, "grp_fu_137_p2");
    sc_trace(mVcdFile, tmp_8_reg_278, "tmp_8_reg_278");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage5, "ap_CS_fsm_pp0_stage5");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage5_iter0, "ap_block_state9_pp0_stage5_iter0");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage5_iter1, "ap_block_state16_pp0_stage5_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage5_flag00011001, "ap_block_pp0_stage5_flag00011001");
    sc_trace(mVcdFile, grp_fu_132_p2, "grp_fu_132_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011011, "ap_block_pp0_stage0_flag00011011");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage6_iter0, "ap_block_state10_pp0_stage6_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage6_flag00011011, "ap_block_pp0_stage6_flag00011011");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage6, "ap_CS_fsm_pp0_stage6");
    sc_trace(mVcdFile, ap_block_pp0_stage5_flag00011011, "ap_block_pp0_stage5_flag00011011");
    sc_trace(mVcdFile, o_1_reg_98, "o_1_reg_98");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, i_1_phi_fu_114_p4, "i_1_phi_fu_114_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00000000, "ap_block_pp0_stage0_flag00000000");
    sc_trace(mVcdFile, tmp_9_cast_fu_175_p1, "tmp_9_cast_fu_175_p1");
    sc_trace(mVcdFile, tmp_10_cast_fu_199_p1, "tmp_10_cast_fu_199_p1");
    sc_trace(mVcdFile, tmp_4_cast_fu_210_p1, "tmp_4_cast_fu_210_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage6_flag00000000, "ap_block_pp0_stage6_flag00000000");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_pp0_stage2_flag00000000, "ap_block_pp0_stage2_flag00000000");
    sc_trace(mVcdFile, tmp_fu_157_p3, "tmp_fu_157_p3");
    sc_trace(mVcdFile, tmp_1_cast_fu_153_p1, "tmp_1_cast_fu_153_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_165_p1, "p_shl_cast_fu_165_p1");
    sc_trace(mVcdFile, tmp_cast_fu_190_p1, "tmp_cast_fu_190_p1");
    sc_trace(mVcdFile, tmp_s_fu_194_p2, "tmp_s_fu_194_p2");
    sc_trace(mVcdFile, tmp_4_fu_204_p2, "tmp_4_fu_204_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage1_flag00011011, "ap_block_pp0_stage1_flag00011011");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage2_iter0, "ap_block_state6_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage2_iter1, "ap_block_state13_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage2_flag00011011, "ap_block_pp0_stage2_flag00011011");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage3_iter0, "ap_block_state7_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage3_iter1, "ap_block_state14_pp0_stage3_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage3_flag00011011, "ap_block_pp0_stage3_flag00011011");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage4_iter0, "ap_block_state8_pp0_stage4_iter0");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage4_iter1, "ap_block_state15_pp0_stage4_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage4_flag00011011, "ap_block_pp0_stage4_flag00011011");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

Loop_ho_loop_proc::~Loop_ho_loop_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete hiddenToOutputWeight_U;
    delete digitRecognizer_fcud_x_U6;
    delete digitRecognizer_fdEe_x_U7;
}

void Loop_ho_loop_proc::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void Loop_ho_loop_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(exitcond1_fu_141_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()) && 
             ((esl_seteq<1,1,1>(ap_block_pp0_stage6_flag00011011.read(), ap_const_boolean_0) && 
               esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage6.read())) || 
              (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
               esl_seteq<1,1,1>(ap_block_pp0_stage5_flag00011011.read(), ap_const_boolean_0))))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state4.read() ^ ap_const_logic_1);
        } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage6_flag00011011.read(), ap_const_boolean_0) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage6.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
                     esl_seteq<1,1,1>(ap_block_pp0_stage5_flag00011011.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_249.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i_1_reg_110 = i_reg_263.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_1_reg_110 = ap_const_lv6_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        o_1_reg_98 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        o_1_reg_98 = o_reg_224.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage5_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_reg_249.read()))) {
        sum1_reg_121 = grp_fu_132_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sum1_reg_121 = hiddenToOutputWeight_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_exitcond_reg_249 = exitcond_reg_249.read();
        exitcond_reg_249 = exitcond_fu_184_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_249.read()))) {
        hiddenOut_load_reg_273 = hiddenOut_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_249.read()))) {
        hiddenToOutputWeight_2_reg_268 = hiddenToOutputWeight_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_184_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        i_reg_263 = i_fu_215_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        o_reg_224 = o_fu_147_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_1_reg_239 = tmp_1_fu_180_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_249.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage5_flag00011001.read(), ap_const_boolean_0))) {
        tmp_8_reg_278 = grp_fu_137_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_141_p2.read(), ap_const_lv1_0))) {
        tmp_9_reg_229 = tmp_9_fu_169_p2.read();
    }
}

void Loop_ho_loop_proc::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void Loop_ho_loop_proc::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[4];
}

void Loop_ho_loop_proc::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[5];
}

void Loop_ho_loop_proc::thread_ap_CS_fsm_pp0_stage5() {
    ap_CS_fsm_pp0_stage5 = ap_CS_fsm.read()[8];
}

void Loop_ho_loop_proc::thread_ap_CS_fsm_pp0_stage6() {
    ap_CS_fsm_pp0_stage6 = ap_CS_fsm.read()[9];
}

void Loop_ho_loop_proc::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_ho_loop_proc::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[10];
}

void Loop_ho_loop_proc::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Loop_ho_loop_proc::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage0_flag00000000() {
    ap_block_pp0_stage0_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage0_flag00011001() {
    ap_block_pp0_stage0_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage0_flag00011011() {
    ap_block_pp0_stage0_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage1_flag00011001() {
    ap_block_pp0_stage1_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage1_flag00011011() {
    ap_block_pp0_stage1_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage2_flag00000000() {
    ap_block_pp0_stage2_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage2_flag00011011() {
    ap_block_pp0_stage2_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage3_flag00011011() {
    ap_block_pp0_stage3_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage4_flag00011011() {
    ap_block_pp0_stage4_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage5_flag00011001() {
    ap_block_pp0_stage5_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage5_flag00011011() {
    ap_block_pp0_stage5_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage6_flag00000000() {
    ap_block_pp0_stage6_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_pp0_stage6_flag00011011() {
    ap_block_pp0_stage6_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Loop_ho_loop_proc::thread_ap_block_state10_pp0_stage6_iter0() {
    ap_block_state10_pp0_stage6_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state11_pp0_stage0_iter1() {
    ap_block_state11_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state12_pp0_stage1_iter1() {
    ap_block_state12_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state13_pp0_stage2_iter1() {
    ap_block_state13_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state14_pp0_stage3_iter1() {
    ap_block_state14_pp0_stage3_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state15_pp0_stage4_iter1() {
    ap_block_state15_pp0_stage4_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state16_pp0_stage5_iter1() {
    ap_block_state16_pp0_stage5_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state5_pp0_stage1_iter0() {
    ap_block_state5_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state6_pp0_stage2_iter0() {
    ap_block_state6_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state7_pp0_stage3_iter0() {
    ap_block_state7_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state8_pp0_stage4_iter0() {
    ap_block_state8_pp0_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_block_state9_pp0_stage5_iter0() {
    ap_block_state9_pp0_stage5_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_ho_loop_proc::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(exitcond_fu_184_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void Loop_ho_loop_proc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_141_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_ho_loop_proc::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Loop_ho_loop_proc::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_ho_loop_proc::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Loop_ho_loop_proc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_141_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_ho_loop_proc::thread_exitcond1_fu_141_p2() {
    exitcond1_fu_141_p2 = (!o_1_reg_98.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(o_1_reg_98.read() == ap_const_lv4_A);
}

void Loop_ho_loop_proc::thread_exitcond_fu_184_p2() {
    exitcond_fu_184_p2 = (!i_1_phi_fu_114_p4.read().is_01() || !ap_const_lv6_21.is_01())? sc_lv<1>(): sc_lv<1>(i_1_phi_fu_114_p4.read() == ap_const_lv6_21);
}

void Loop_ho_loop_proc::thread_hiddenOut_address0() {
    hiddenOut_address0 =  (sc_lv<5>) (tmp_4_cast_fu_210_p1.read());
}

void Loop_ho_loop_proc::thread_hiddenOut_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        hiddenOut_ce0 = ap_const_logic_1;
    } else {
        hiddenOut_ce0 = ap_const_logic_0;
    }
}

void Loop_ho_loop_proc::thread_hiddenToOutputWeight_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00000000.read(), ap_const_boolean_0))) {
        hiddenToOutputWeight_address0 =  (sc_lv<9>) (tmp_10_cast_fu_199_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        hiddenToOutputWeight_address0 =  (sc_lv<9>) (tmp_9_cast_fu_175_p1.read());
    } else {
        hiddenToOutputWeight_address0 = "XXXXXXXXX";
    }
}

void Loop_ho_loop_proc::thread_hiddenToOutputWeight_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())))) {
        hiddenToOutputWeight_ce0 = ap_const_logic_1;
    } else {
        hiddenToOutputWeight_ce0 = ap_const_logic_0;
    }
}

void Loop_ho_loop_proc::thread_i_1_phi_fu_114_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_249.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00000000.read(), ap_const_boolean_0))) {
        i_1_phi_fu_114_p4 = i_reg_263.read();
    } else {
        i_1_phi_fu_114_p4 = i_1_reg_110.read();
    }
}

void Loop_ho_loop_proc::thread_i_fu_215_p2() {
    i_fu_215_p2 = (!i_1_phi_fu_114_p4.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_1_phi_fu_114_p4.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void Loop_ho_loop_proc::thread_o_fu_147_p2() {
    o_fu_147_p2 = (!o_1_reg_98.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(o_1_reg_98.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Loop_ho_loop_proc::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<4>) (tmp_1_reg_239.read());
}

void Loop_ho_loop_proc::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void Loop_ho_loop_proc::thread_output_r_d0() {
    output_r_d0 = sum1_reg_121.read();
}

void Loop_ho_loop_proc::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void Loop_ho_loop_proc::thread_p_shl_cast_fu_165_p1() {
    p_shl_cast_fu_165_p1 = esl_zext<10,9>(tmp_fu_157_p3.read());
}

void Loop_ho_loop_proc::thread_tmp_10_cast_fu_199_p1() {
    tmp_10_cast_fu_199_p1 = esl_zext<32,10>(tmp_s_fu_194_p2.read());
}

void Loop_ho_loop_proc::thread_tmp_1_cast_fu_153_p1() {
    tmp_1_cast_fu_153_p1 = esl_zext<10,4>(o_1_reg_98.read());
}

void Loop_ho_loop_proc::thread_tmp_1_fu_180_p1() {
    tmp_1_fu_180_p1 = esl_zext<32,4>(o_1_reg_98.read());
}

void Loop_ho_loop_proc::thread_tmp_4_cast_fu_210_p1() {
    tmp_4_cast_fu_210_p1 = esl_zext<32,6>(tmp_4_fu_204_p2.read());
}

void Loop_ho_loop_proc::thread_tmp_4_fu_204_p2() {
    tmp_4_fu_204_p2 = (!i_1_phi_fu_114_p4.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(i_1_phi_fu_114_p4.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void Loop_ho_loop_proc::thread_tmp_9_cast_fu_175_p1() {
    tmp_9_cast_fu_175_p1 = esl_zext<32,10>(tmp_9_fu_169_p2.read());
}

void Loop_ho_loop_proc::thread_tmp_9_fu_169_p2() {
    tmp_9_fu_169_p2 = (!tmp_1_cast_fu_153_p1.read().is_01() || !p_shl_cast_fu_165_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(tmp_1_cast_fu_153_p1.read()) + sc_biguint<10>(p_shl_cast_fu_165_p1.read()));
}

void Loop_ho_loop_proc::thread_tmp_cast_fu_190_p1() {
    tmp_cast_fu_190_p1 = esl_zext<10,6>(i_1_phi_fu_114_p4.read());
}

void Loop_ho_loop_proc::thread_tmp_fu_157_p3() {
    tmp_fu_157_p3 = esl_concat<4,5>(o_1_reg_98.read(), ap_const_lv5_0);
}

void Loop_ho_loop_proc::thread_tmp_s_fu_194_p2() {
    tmp_s_fu_194_p2 = (!tmp_9_reg_229.read().is_01() || !tmp_cast_fu_190_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(tmp_9_reg_229.read()) + sc_biguint<10>(tmp_cast_fu_190_p1.read()));
}

void Loop_ho_loop_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_141_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_fu_184_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_fu_184_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011011.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 32 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_flag00011011.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 64 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_flag00011011.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 128 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage4_flag00011011.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage5_flag00011011.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage5_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage5_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            }
            break;
        case 512 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage6_flag00011011.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

