// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XDIGITRECOGNIZER_H
#define XDIGITRECOGNIZER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdigitrecognizer_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Digrec_io_BaseAddress;
} XDigitrecognizer_Config;
#endif

typedef struct {
    u32 Digrec_io_BaseAddress;
    u32 IsReady;
} XDigitrecognizer;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDigitrecognizer_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDigitrecognizer_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDigitrecognizer_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDigitrecognizer_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDigitrecognizer_Initialize(XDigitrecognizer *InstancePtr, u16 DeviceId);
XDigitrecognizer_Config* XDigitrecognizer_LookupConfig(u16 DeviceId);
int XDigitrecognizer_CfgInitialize(XDigitrecognizer *InstancePtr, XDigitrecognizer_Config *ConfigPtr);
#else
int XDigitrecognizer_Initialize(XDigitrecognizer *InstancePtr, const char* InstanceName);
int XDigitrecognizer_Release(XDigitrecognizer *InstancePtr);
#endif

void XDigitrecognizer_Start(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_IsDone(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_IsIdle(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_IsReady(XDigitrecognizer *InstancePtr);
void XDigitrecognizer_EnableAutoRestart(XDigitrecognizer *InstancePtr);
void XDigitrecognizer_DisableAutoRestart(XDigitrecognizer *InstancePtr);

u32 XDigitrecognizer_Get_inputData_BaseAddress(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Get_inputData_HighAddress(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Get_inputData_TotalBytes(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Get_inputData_BitWidth(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Get_inputData_Depth(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Write_inputData_Words(XDigitrecognizer *InstancePtr, int offset, int *data, int length);
u32 XDigitrecognizer_Read_inputData_Words(XDigitrecognizer *InstancePtr, int offset, int *data, int length);
u32 XDigitrecognizer_Write_inputData_Bytes(XDigitrecognizer *InstancePtr, int offset, char *data, int length);
u32 XDigitrecognizer_Read_inputData_Bytes(XDigitrecognizer *InstancePtr, int offset, char *data, int length);
u32 XDigitrecognizer_Get_output_r_BaseAddress(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Get_output_r_HighAddress(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Get_output_r_TotalBytes(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Get_output_r_BitWidth(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Get_output_r_Depth(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_Write_output_r_Words(XDigitrecognizer *InstancePtr, int offset, int *data, int length);
u32 XDigitrecognizer_Read_output_r_Words(XDigitrecognizer *InstancePtr, int offset, int *data, int length);
u32 XDigitrecognizer_Write_output_r_Bytes(XDigitrecognizer *InstancePtr, int offset, char *data, int length);
u32 XDigitrecognizer_Read_output_r_Bytes(XDigitrecognizer *InstancePtr, int offset, char *data, int length);

void XDigitrecognizer_InterruptGlobalEnable(XDigitrecognizer *InstancePtr);
void XDigitrecognizer_InterruptGlobalDisable(XDigitrecognizer *InstancePtr);
void XDigitrecognizer_InterruptEnable(XDigitrecognizer *InstancePtr, u32 Mask);
void XDigitrecognizer_InterruptDisable(XDigitrecognizer *InstancePtr, u32 Mask);
void XDigitrecognizer_InterruptClear(XDigitrecognizer *InstancePtr, u32 Mask);
u32 XDigitrecognizer_InterruptGetEnabled(XDigitrecognizer *InstancePtr);
u32 XDigitrecognizer_InterruptGetStatus(XDigitrecognizer *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
