#pragma line 1 "layer_hls/src/digitRecognizer.cpp" ::: 0
#pragma line 1 "layer_hls/src/digitRecognizer.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 153 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 145 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 65
#pragma line 156 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 68
#pragma line 413 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 198
#pragma line 427 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 201
#pragma line 8 "<command line>" 2 ::: 203
#pragma line 1 "<built-in>" 2 ::: 204
#pragma line 1 "layer_hls/src/digitRecognizer.cpp" 2 ::: 205
#pragma line 1 "layer_hls/src/digitRecognizer.h" 1 ::: 206
#pragma line 1 "layer_hls/src/nn_3_layers_32_neurons.h" 1 ::: 210
#pragma line 1 "layer_hls/src/types.h" 1 ::: 231
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 1 ::: 240
#pragma line 62 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 293
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 294
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 304
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 315
#pragma line 18 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 321
#pragma line 47 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 326
#pragma line 62 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 328
#pragma line 79 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 335
#pragma line 10 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 338
#pragma line 32 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 342
#pragma line 147 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 345
#pragma line 225 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 349
#pragma line 277 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 351
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 352
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 366
#pragma line 674 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 372
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 373
#pragma line 674 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 374
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 376
#pragma line 675 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 377
#pragma line 13 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 378
#pragma line 46 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 398
#pragma line 99 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 400
#pragma line 277 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 405
#pragma line 316 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 409
#pragma line 372 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 415
#pragma line 382 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 417
#pragma line 394 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 419
#pragma line 407 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 421
#pragma line 420 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 423
#pragma line 436 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 425
#pragma line 456 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 428
#pragma line 518 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 446
#pragma line 605 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 460
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 524
#pragma line 36 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 3 ::: 529
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 1 3 ::: 670
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 680
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 2 3 ::: 686
#pragma line 175 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 687
#pragma line 63 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 688
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 689
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 699
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 705
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 708
#pragma line 11 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 716
#pragma line 26 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 723
#pragma line 84 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 735
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 748
#pragma line 120 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 750
#pragma line 157 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 752
#pragma line 312 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 898
#pragma line 330 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 906
#pragma line 373 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 942
#pragma line 417 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 977
#pragma line 475 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1007
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1043
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1053
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1059
#pragma line 509 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1060
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1063
#pragma line 511 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1071
#pragma line 64 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 1072
#pragma line 77 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 1073
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1074
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 1 ::: 1132
#pragma line 97 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 1186
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 1187
#pragma line 98 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 2226
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 2227
#pragma line 99 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 3254
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 3255
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 3256
#pragma line 109 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 4295
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 4296
#pragma line 110 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 5323
#pragma line 147 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5334
#pragma line 58 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5336
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" 1 ::: 5337
#pragma line 98 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5390
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5392
#pragma line 129 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5394
#pragma line 143 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5399
#pragma line 156 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5402
#pragma line 192 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5404
#pragma line 358 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5406
#pragma line 59 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5408
#pragma line 85 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 5409
#pragma line 114 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 5411
#pragma line 78 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 5413
#pragma line 88 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 5414
#pragma line 9 "layer_hls/src/types.h" 2 ::: 5416
#pragma line 21 "layer_hls/src/nn_3_layers_32_neurons.h" 2 ::: 5422
#pragma line 5 "layer_hls/src/digitRecognizer.h" 2 ::: 14055
#pragma line 2 "layer_hls/src/digitRecognizer.cpp" 2 ::: 14058
