#pragma line 1 "layer_hls/src/maths.cpp" ::: -10
#pragma line 1 "layer_hls/src/maths.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 153 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 145 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 55
#pragma line 156 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 58
#pragma line 413 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 188
#pragma line 427 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 191
#pragma line 8 "<command line>" 2 ::: 193
#pragma line 1 "<built-in>" 2 ::: 194
#pragma line 1 "layer_hls/src/maths.cpp" 2 ::: 195
#pragma line 1 "layer_hls/src/maths.h" 1 ::: 196
#pragma line 1 "layer_hls/src/types.h" 1 ::: 197
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 1 ::: 206
#pragma line 62 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 259
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 260
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 270
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 281
#pragma line 18 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 287
#pragma line 47 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 292
#pragma line 62 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 294
#pragma line 79 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 301
#pragma line 10 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 304
#pragma line 32 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 308
#pragma line 147 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 311
#pragma line 225 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 315
#pragma line 277 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 317
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 318
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 332
#pragma line 674 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 338
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 339
#pragma line 674 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 340
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 342
#pragma line 675 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 343
#pragma line 13 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 344
#pragma line 46 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 364
#pragma line 99 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 366
#pragma line 277 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 371
#pragma line 316 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 375
#pragma line 372 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 381
#pragma line 382 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 383
#pragma line 394 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 385
#pragma line 407 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 387
#pragma line 420 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 389
#pragma line 436 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 391
#pragma line 456 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 394
#pragma line 518 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 412
#pragma line 605 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 426
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 490
#pragma line 36 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 3 ::: 495
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 1 3 ::: 636
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 646
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 2 3 ::: 652
#pragma line 175 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 653
#pragma line 63 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 654
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 655
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 665
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 671
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 674
#pragma line 11 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 682
#pragma line 26 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 689
#pragma line 84 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 701
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 714
#pragma line 120 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 716
#pragma line 157 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 718
#pragma line 312 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 864
#pragma line 330 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 872
#pragma line 373 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 908
#pragma line 417 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 943
#pragma line 475 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 973
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1009
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1019
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1025
#pragma line 509 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1026
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1029
#pragma line 511 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1037
#pragma line 64 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 1038
#pragma line 77 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 1039
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1040
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 1 ::: 1098
#pragma line 97 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 1152
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 1153
#pragma line 98 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 2192
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 2193
#pragma line 99 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 3220
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 3221
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 3222
#pragma line 109 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 4261
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 4262
#pragma line 110 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 5289
#pragma line 147 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5300
#pragma line 58 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5302
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" 1 ::: 5303
#pragma line 98 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5356
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5358
#pragma line 129 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5360
#pragma line 143 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5365
#pragma line 156 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5368
#pragma line 192 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5370
#pragma line 358 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5372
#pragma line 59 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5374
#pragma line 85 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 5375
#pragma line 114 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 5377
#pragma line 78 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 5379
#pragma line 88 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 5380
#pragma line 9 "layer_hls/src/types.h" 2 ::: 5382
#pragma line 2 "layer_hls/src/maths.h" 2 ::: 5388
#pragma line 2 "layer_hls/src/maths.cpp" 2 ::: 5395
