#pragma line 1 "layer_hls/src/maths.cpp" ::: 0
#pragma line 1 "layer_hls/src/maths.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 153 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 145 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 65
#pragma line 156 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 68
#pragma line 413 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 198
#pragma line 427 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 201
#pragma line 8 "<command line>" 2 ::: 203
#pragma line 1 "<built-in>" 2 ::: 204
#pragma line 1 "layer_hls/src/maths.cpp" 2 ::: 205
#pragma line 1 "layer_hls/src/maths.h" 1 ::: 206
#pragma line 1 "layer_hls/src/types.h" 1 ::: 207
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 1 ::: 216
#pragma line 62 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 269
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 270
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 280
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 291
#pragma line 18 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 297
#pragma line 47 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 302
#pragma line 62 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 304
#pragma line 79 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 311
#pragma line 10 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 314
#pragma line 32 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 318
#pragma line 147 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 321
#pragma line 225 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 325
#pragma line 277 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 327
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 328
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 342
#pragma line 674 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 348
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 349
#pragma line 674 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 350
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 352
#pragma line 675 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 353
#pragma line 13 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 354
#pragma line 46 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 374
#pragma line 99 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 376
#pragma line 277 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 381
#pragma line 316 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 385
#pragma line 372 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 391
#pragma line 382 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 393
#pragma line 394 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 395
#pragma line 407 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 397
#pragma line 420 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 399
#pragma line 436 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 401
#pragma line 456 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 404
#pragma line 518 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 422
#pragma line 605 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 436
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 500
#pragma line 36 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 3 ::: 505
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 1 3 ::: 646
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 656
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 2 3 ::: 662
#pragma line 175 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 663
#pragma line 63 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 664
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 665
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 675
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 681
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 684
#pragma line 11 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 692
#pragma line 26 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 699
#pragma line 84 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 711
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 724
#pragma line 120 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 726
#pragma line 157 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 728
#pragma line 312 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 874
#pragma line 330 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 882
#pragma line 373 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 918
#pragma line 417 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 953
#pragma line 475 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 983
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1019
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1029
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1035
#pragma line 509 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1036
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1039
#pragma line 511 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1047
#pragma line 64 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 1048
#pragma line 77 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 1049
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1050
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 1 ::: 1108
#pragma line 97 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 1162
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 1163
#pragma line 98 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 2202
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 2203
#pragma line 99 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 3230
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 3231
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 3232
#pragma line 109 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 4271
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 4272
#pragma line 110 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 5299
#pragma line 147 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5310
#pragma line 58 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5312
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" 1 ::: 5313
#pragma line 98 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5366
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5368
#pragma line 129 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5370
#pragma line 143 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5375
#pragma line 156 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5378
#pragma line 192 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5380
#pragma line 358 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5382
#pragma line 59 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5384
#pragma line 85 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 5385
#pragma line 114 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 5387
#pragma line 78 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 5389
#pragma line 88 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 5390
#pragma line 9 "layer_hls/src/types.h" 2 ::: 5392
#pragma line 2 "layer_hls/src/maths.h" 2 ::: 5398
#pragma line 2 "layer_hls/src/maths.cpp" 2 ::: 5405
