lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/asserts.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/asserts.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/asserts.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/asserts.cpp" location "Neuron_compute/Neuron_compute_loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'Neuron_compute' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/input.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/input.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/input.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/input.cpp" location "Neuron_compute/Neuron_compute_loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'Neuron_compute' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/maths.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/maths.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/maths.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/maths.cpp" location "Neuron_compute/Neuron_compute_loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'Neuron_compute' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/neuron.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/neuron.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/neuron.cpp" location "neuronInitAndCompute3HardCoded" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neuronInitAndCompute3HardCoded' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/neuron.cpp" location "Neuron_compute/Neuron_compute_loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/neuron_main.cpp" location "neuronInitAndCompute3HardCoded" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/neuron_main.cpp" location "neuronInitAndCompute3HardCoded" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/neuron_main.cpp" location "neuronInitAndCompute3HardCoded" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_neuron/neuron_hls/src/neuron_main.cpp" location "Neuron_compute/Neuron_compute_loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'Neuron_compute' does not exist in any synthesis source file."}
