# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/solution4/impl/vhdl/digitRecognizer.xdc

# IP: ip/digitRecognizer_ap_fcmp_0_no_dsp_32/digitRecognizer_ap_fcmp_0_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==digitRecognizer_ap_fcmp_0_no_dsp_32 || ORIG_REF_NAME==digitRecognizer_ap_fcmp_0_no_dsp_32}]

# IP: ip/digitRecognizer_ap_fmul_2_max_dsp_32/digitRecognizer_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==digitRecognizer_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==digitRecognizer_ap_fmul_2_max_dsp_32}]

# IP: ip/digitRecognizer_ap_fadd_5_full_dsp_32/digitRecognizer_ap_fadd_5_full_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==digitRecognizer_ap_fadd_5_full_dsp_32 || ORIG_REF_NAME==digitRecognizer_ap_fadd_5_full_dsp_32}]
