#pragma line 1 "nn_hls/src/digitRecognizer.cpp" ::: -10
#pragma line 1 "nn_hls/src/digitRecognizer.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 153 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 145 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 55
#pragma line 156 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 58
#pragma line 413 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 188
#pragma line 427 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 191
#pragma line 8 "<command line>" 2 ::: 193
#pragma line 1 "<built-in>" 2 ::: 194
#pragma line 1 "nn_hls/src/digitRecognizer.cpp" 2 ::: 195
#pragma line 1 "nn_hls/src/digitRecognizer.h" 1 ::: 196
#pragma line 1 "nn_hls/src/nn_3_layers_32_neurons.h" 1 ::: 200
#pragma line 1 "nn_hls/src/types.h" 1 ::: 221
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 1 ::: 230
#pragma line 62 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 283
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 284
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 294
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 305
#pragma line 18 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 311
#pragma line 47 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 316
#pragma line 62 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 318
#pragma line 79 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 325
#pragma line 10 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 328
#pragma line 32 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 332
#pragma line 147 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 335
#pragma line 225 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 339
#pragma line 277 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 341
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 342
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 356
#pragma line 674 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 362
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 363
#pragma line 674 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 364
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 366
#pragma line 675 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 367
#pragma line 13 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 368
#pragma line 46 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 388
#pragma line 99 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 390
#pragma line 277 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 395
#pragma line 316 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 399
#pragma line 372 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 405
#pragma line 382 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 407
#pragma line 394 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 409
#pragma line 407 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 411
#pragma line 420 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 413
#pragma line 436 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 415
#pragma line 456 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 418
#pragma line 518 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 436
#pragma line 605 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 450
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 514
#pragma line 36 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 3 ::: 519
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 1 3 ::: 660
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 670
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 2 3 ::: 676
#pragma line 175 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 677
#pragma line 63 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 678
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 679
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 689
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 695
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 698
#pragma line 11 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 706
#pragma line 26 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 713
#pragma line 84 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 725
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 738
#pragma line 120 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 740
#pragma line 157 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 742
#pragma line 312 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 888
#pragma line 330 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 896
#pragma line 373 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 932
#pragma line 417 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 967
#pragma line 475 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 997
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1033
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1043
#pragma line 9 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1049
#pragma line 509 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1050
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1053
#pragma line 511 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1061
#pragma line 64 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 1062
#pragma line 77 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 1063
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1064
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 1 ::: 1122
#pragma line 97 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 1176
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 1177
#pragma line 98 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 2216
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 2217
#pragma line 99 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 3244
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 3245
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 3246
#pragma line 109 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 4285
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 4286
#pragma line 110 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 5313
#pragma line 147 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5324
#pragma line 58 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5326
#pragma line 1 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" 1 ::: 5327
#pragma line 98 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5380
#pragma line 108 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5382
#pragma line 129 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5384
#pragma line 143 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5389
#pragma line 156 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5392
#pragma line 192 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5394
#pragma line 358 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5396
#pragma line 59 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5398
#pragma line 85 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 5399
#pragma line 114 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 5401
#pragma line 78 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" 2 ::: 5403
#pragma line 88 "C:/Users/Lukas/Documents/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot\\ap_cint.h" ::: 5404
#pragma line 9 "nn_hls/src/types.h" 2 ::: 5406
#pragma line 21 "nn_hls/src/nn_3_layers_32_neurons.h" 2 ::: 5412
#pragma line 5 "nn_hls/src/digitRecognizer.h" 2 ::: 14045
#pragma line 2 "nn_hls/src/digitRecognizer.cpp" 2 ::: 14048
#pragma line 3 "nn_hls/src/digitRecognizer.cpp" ::: 14052
#pragma line 3 "nn_hls/src/digitRecognizer.cpp" ::: 14055
#pragma line 3 "nn_hls/src/digitRecognizer.cpp" ::: 14058
#pragma line 13 "nn_hls/src/digitRecognizer.cpp" ::: 14071
#pragma line 25 "nn_hls/src/digitRecognizer.cpp" ::: 14086
