lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "nn" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'nn' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "nn" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'nn' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "nn" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'nn' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "digitRecognizer/smt_loop" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'smt_loop' does not exist in function 'digitRecognizer'. "}
lappend pragmaStatus4 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "digitRecognizer/smo_loop" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'smo_loop' does not exist in function 'digitRecognizer'. "}
lappend pragmaStatus5 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "expApprox/approx_loop/exp_approx" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'expApprox' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "digitRecognizer/hn_loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "digitRecognizer/on_loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "digitRecognizer" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "digitRecognizer" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "INTERFACE" source "C:/Users/Lukas/Desktop/embedded-rts/project/synthesize_nn/nn_hls/src/digitRecognizer.cpp" location "digitRecognizer" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
