// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="digitRecognizer,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.789000,HLS_SYN_LAT=178269,HLS_SYN_TPT=175938,HLS_SYN_MEM=71,HLS_SYN_DSP=10,HLS_SYN_FF=1880,HLS_SYN_LUT=2409}" *)

module digitRecognizer (
        s_axi_digrec_io_AWVALID,
        s_axi_digrec_io_AWREADY,
        s_axi_digrec_io_AWADDR,
        s_axi_digrec_io_WVALID,
        s_axi_digrec_io_WREADY,
        s_axi_digrec_io_WDATA,
        s_axi_digrec_io_WSTRB,
        s_axi_digrec_io_ARVALID,
        s_axi_digrec_io_ARREADY,
        s_axi_digrec_io_ARADDR,
        s_axi_digrec_io_RVALID,
        s_axi_digrec_io_RREADY,
        s_axi_digrec_io_RDATA,
        s_axi_digrec_io_RRESP,
        s_axi_digrec_io_BVALID,
        s_axi_digrec_io_BREADY,
        s_axi_digrec_io_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt
);

parameter    C_S_AXI_DIGREC_IO_DATA_WIDTH = 32;
parameter    C_S_AXI_DIGREC_IO_ADDR_WIDTH = 14;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_DIGREC_IO_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_digrec_io_AWVALID;
output   s_axi_digrec_io_AWREADY;
input  [C_S_AXI_DIGREC_IO_ADDR_WIDTH - 1:0] s_axi_digrec_io_AWADDR;
input   s_axi_digrec_io_WVALID;
output   s_axi_digrec_io_WREADY;
input  [C_S_AXI_DIGREC_IO_DATA_WIDTH - 1:0] s_axi_digrec_io_WDATA;
input  [C_S_AXI_DIGREC_IO_WSTRB_WIDTH - 1:0] s_axi_digrec_io_WSTRB;
input   s_axi_digrec_io_ARVALID;
output   s_axi_digrec_io_ARREADY;
input  [C_S_AXI_DIGREC_IO_ADDR_WIDTH - 1:0] s_axi_digrec_io_ARADDR;
output   s_axi_digrec_io_RVALID;
input   s_axi_digrec_io_RREADY;
output  [C_S_AXI_DIGREC_IO_DATA_WIDTH - 1:0] s_axi_digrec_io_RDATA;
output  [1:0] s_axi_digrec_io_RRESP;
output   s_axi_digrec_io_BVALID;
input   s_axi_digrec_io_BREADY;
output  [1:0] s_axi_digrec_io_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [31:0] inputData_q0;
wire   [31:0] hiddenOut_i_q0;
wire   [31:0] hiddenOut_t_q0;
wire    Loop_ih_loop_proc_U0_ap_start;
wire    Loop_ih_loop_proc_U0_ap_done;
wire    Loop_ih_loop_proc_U0_ap_continue;
wire    Loop_ih_loop_proc_U0_ap_idle;
wire    Loop_ih_loop_proc_U0_ap_ready;
wire   [4:0] Loop_ih_loop_proc_U0_hiddenOut_address0;
wire    Loop_ih_loop_proc_U0_hiddenOut_ce0;
wire    Loop_ih_loop_proc_U0_hiddenOut_we0;
wire   [31:0] Loop_ih_loop_proc_U0_hiddenOut_d0;
wire   [9:0] Loop_ih_loop_proc_U0_inputData_address0;
wire    Loop_ih_loop_proc_U0_inputData_ce0;
wire    ap_channel_done_hiddenOut;
wire    Loop_ih_loop_proc_U0_hiddenOut_full_n;
wire    Loop_ho_loop_proc_U0_ap_start;
wire    Loop_ho_loop_proc_U0_ap_done;
wire    Loop_ho_loop_proc_U0_ap_continue;
wire    Loop_ho_loop_proc_U0_ap_idle;
wire    Loop_ho_loop_proc_U0_ap_ready;
wire   [3:0] Loop_ho_loop_proc_U0_output_r_address0;
wire    Loop_ho_loop_proc_U0_output_r_ce0;
wire    Loop_ho_loop_proc_U0_output_r_we0;
wire   [31:0] Loop_ho_loop_proc_U0_output_r_d0;
wire   [4:0] Loop_ho_loop_proc_U0_hiddenOut_address0;
wire    Loop_ho_loop_proc_U0_hiddenOut_ce0;
wire    ap_sync_continue;
wire    hiddenOut_i_full_n;
wire    hiddenOut_t_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    Loop_ih_loop_proc_U0_start_full_n;
wire    Loop_ih_loop_proc_U0_start_write;
wire    Loop_ho_loop_proc_U0_start_full_n;
wire    Loop_ho_loop_proc_U0_start_write;

digitRecognizer_digrec_io_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_DIGREC_IO_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_DIGREC_IO_DATA_WIDTH ))
digitRecognizer_digrec_io_s_axi_U(
    .AWVALID(s_axi_digrec_io_AWVALID),
    .AWREADY(s_axi_digrec_io_AWREADY),
    .AWADDR(s_axi_digrec_io_AWADDR),
    .WVALID(s_axi_digrec_io_WVALID),
    .WREADY(s_axi_digrec_io_WREADY),
    .WDATA(s_axi_digrec_io_WDATA),
    .WSTRB(s_axi_digrec_io_WSTRB),
    .ARVALID(s_axi_digrec_io_ARVALID),
    .ARREADY(s_axi_digrec_io_ARREADY),
    .ARADDR(s_axi_digrec_io_ARADDR),
    .RVALID(s_axi_digrec_io_RVALID),
    .RREADY(s_axi_digrec_io_RREADY),
    .RDATA(s_axi_digrec_io_RDATA),
    .RRESP(s_axi_digrec_io_RRESP),
    .BVALID(s_axi_digrec_io_BVALID),
    .BREADY(s_axi_digrec_io_BREADY),
    .BRESP(s_axi_digrec_io_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .inputData_address0(Loop_ih_loop_proc_U0_inputData_address0),
    .inputData_ce0(Loop_ih_loop_proc_U0_inputData_ce0),
    .inputData_q0(inputData_q0),
    .output_r_address0(Loop_ho_loop_proc_U0_output_r_address0),
    .output_r_ce0(Loop_ho_loop_proc_U0_output_r_ce0),
    .output_r_we0(Loop_ho_loop_proc_U0_output_r_we0),
    .output_r_d0(Loop_ho_loop_proc_U0_output_r_d0)
);

digitRecognizer_hg8j #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
hiddenOut_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_ih_loop_proc_U0_hiddenOut_address0),
    .i_ce0(Loop_ih_loop_proc_U0_hiddenOut_ce0),
    .i_we0(Loop_ih_loop_proc_U0_hiddenOut_we0),
    .i_d0(Loop_ih_loop_proc_U0_hiddenOut_d0),
    .i_q0(hiddenOut_i_q0),
    .t_address0(Loop_ho_loop_proc_U0_hiddenOut_address0),
    .t_ce0(Loop_ho_loop_proc_U0_hiddenOut_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(hiddenOut_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(hiddenOut_i_full_n),
    .i_write(Loop_ih_loop_proc_U0_ap_done),
    .t_empty_n(hiddenOut_t_empty_n),
    .t_read(Loop_ho_loop_proc_U0_ap_ready)
);

Loop_ih_loop_proc Loop_ih_loop_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_ih_loop_proc_U0_ap_start),
    .ap_done(Loop_ih_loop_proc_U0_ap_done),
    .ap_continue(Loop_ih_loop_proc_U0_ap_continue),
    .ap_idle(Loop_ih_loop_proc_U0_ap_idle),
    .ap_ready(Loop_ih_loop_proc_U0_ap_ready),
    .hiddenOut_address0(Loop_ih_loop_proc_U0_hiddenOut_address0),
    .hiddenOut_ce0(Loop_ih_loop_proc_U0_hiddenOut_ce0),
    .hiddenOut_we0(Loop_ih_loop_proc_U0_hiddenOut_we0),
    .hiddenOut_d0(Loop_ih_loop_proc_U0_hiddenOut_d0),
    .inputData_address0(Loop_ih_loop_proc_U0_inputData_address0),
    .inputData_ce0(Loop_ih_loop_proc_U0_inputData_ce0),
    .inputData_q0(inputData_q0)
);

Loop_ho_loop_proc Loop_ho_loop_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_ho_loop_proc_U0_ap_start),
    .ap_done(Loop_ho_loop_proc_U0_ap_done),
    .ap_continue(Loop_ho_loop_proc_U0_ap_continue),
    .ap_idle(Loop_ho_loop_proc_U0_ap_idle),
    .ap_ready(Loop_ho_loop_proc_U0_ap_ready),
    .output_r_address0(Loop_ho_loop_proc_U0_output_r_address0),
    .output_r_ce0(Loop_ho_loop_proc_U0_output_r_ce0),
    .output_r_we0(Loop_ho_loop_proc_U0_output_r_we0),
    .output_r_d0(Loop_ho_loop_proc_U0_output_r_d0),
    .hiddenOut_address0(Loop_ho_loop_proc_U0_hiddenOut_address0),
    .hiddenOut_ce0(Loop_ho_loop_proc_U0_hiddenOut_ce0),
    .hiddenOut_q0(hiddenOut_t_q0)
);

assign Loop_ho_loop_proc_U0_ap_continue = 1'b1;

assign Loop_ho_loop_proc_U0_ap_start = hiddenOut_t_empty_n;

assign Loop_ho_loop_proc_U0_start_full_n = 1'b0;

assign Loop_ho_loop_proc_U0_start_write = 1'b0;

assign Loop_ih_loop_proc_U0_ap_continue = hiddenOut_i_full_n;

assign Loop_ih_loop_proc_U0_ap_start = ap_start;

assign Loop_ih_loop_proc_U0_hiddenOut_full_n = hiddenOut_i_full_n;

assign Loop_ih_loop_proc_U0_start_full_n = 1'b0;

assign Loop_ih_loop_proc_U0_start_write = 1'b0;

assign ap_channel_done_hiddenOut = Loop_ih_loop_proc_U0_ap_done;

assign ap_done = Loop_ho_loop_proc_U0_ap_done;

assign ap_idle = (Loop_ih_loop_proc_U0_ap_idle & Loop_ho_loop_proc_U0_ap_idle & (hiddenOut_t_empty_n ^ 1'b1));

assign ap_ready = Loop_ih_loop_proc_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Loop_ho_loop_proc_U0_ap_done;

assign ap_sync_ready = Loop_ih_loop_proc_U0_ap_ready;

endmodule //digitRecognizer
